### ISSUE TITLE
css问题：position: fixed的一个细节

### ISSUE THREAD

**Issue by wilsonyiyi** [can-you-explain-it-to-me/daily-topic#13]
一直认为position:fixed，设置后，元素脱离文档流，以视口viewport作为自己的父定位容器，今天遇到一个打破该想法的情况。查阅mdn文档后，发现还有一种情况是：
![image](https://user-images.githubusercontent.com/20815934/58856892-6eb52780-86d6-11e9-8fdf-a6466b63f31f.png)

```html
<div class="out">
	<div class="inner"></div>
</div>
```
父元素**未**设置transform属性的情况：
```css
.out{
	width: 500px;
	height: 300px;
	background: lightgreen;
	position: relative;
}

.inner{
	width: 200px;
	height: 100px;
	background: yellow;
	position: fixed;
	right: 0;
	top: 10px;
}
```
![image](https://user-images.githubusercontent.com/20815934/58857162-24807600-86d7-11e9-990a-30e03a6bd34e.png)

父元素设置了transform属性的情况：
```css
.out{
	width: 500px;
	height: 300px;
	background: lightgreen;
	position: relative;
	transform: translate(0px, 0px);
}

.inner{
	width: 200px;
	height: 100px;
	background: yellow;
	position: fixed;
	right: 0;
	top: 10px;
}
```
![image](https://user-images.githubusercontent.com/20815934/58857083-eb480600-86d6-11e9-91c5-db23d64e5269.png)
